name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: leetcode/9_palindrome-number/solution-rust   # <— path to the folder with Cargo.toml
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable  # optional, but nice
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
